name: Build & Release APK
on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.kt"
      - "**/*.xml"
      - "**/*.gradle.kts"
      - "gradle/libs.versions.toml"
      - "gradle/wrapper/**"
      - "gradle.properties"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    uses: mapgie/android-Actions/.github/workflows/android-build-release.yml@87b0b6408e7168235e4977377add51c312ebab71
    with:
      app-name: Dash
