name: Build & Release APK
on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.kt"
      - "**/*.xml"
      - "**/*.gradle.kts"
      - "gradle/libs.versions.toml"
      - "gradle/wrapper/**"
      - "gradle.properties"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    uses: mapgie/android-Actions/.github/workflows/android-build-release.yml@252cf0054ab486b6aa3e87563bc12146d97ff891
    with:
      app-name: Dash
      create-release: ${{ github.event_name == 'workflow_dispatch' }}
