name: Changelog bump check
on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.kt"
      - "**/*.xml"
      - "**/*.gradle.kts"
      - "gradle/libs.versions.toml"
permissions:
  contents: read
jobs:
  check:
    uses: mapgie/android-Actions/.github/workflows/changelog-check.yml@3be8dd368173a146e2355588bd3e1892ef4dd50f
