name: Changelog bump check
on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.kt"
      - "**/*.xml"
      - "**/*.gradle.kts"
      - "gradle/libs.versions.toml"
permissions:
  contents: read
jobs:
  check:
    uses: mapgie/android-Actions/.github/workflows/changelog-check.yml@252cf0054ab486b6aa3e87563bc12146d97ff891
