name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: mapgie/android-Actions/.github/workflows/release.yml@b270387ad758f9886897c0453caf603ebbd03c5e
    with:
      app-name: Dash
