name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: mapgie/android-Actions/.github/workflows/release.yml@d99437fe573b99a7730fd9dcc05c58535143eaf0
    with:
      app-name: Dash
